curlmd/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing.urls')),
    path('workout/', include('workout.urls')),
]

landing/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='landing'),
]

workout/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name='plans'),
    path('add', views.add_plan, name='add_plan'),
    path('view_plan/<str:pk>', views.view_plan, name='view_plan'),
    path('make_active/<str:pk>', views.make_active, name='make_active'),

    path('add_workout/<str:pk>', views.add_workout, name='add_workout'),

    path('add_sets/<str:pk>', views.add_sets, name='add_sets'),

    path('play_workout/<str:pk>', views.play_workout, name='play_workout'),
]

landing/models.py
from django.db import models

# Create your models here.

workout/models.py
from django.db import models


class WorkoutPlan(models.Model):
    STATUS = (
        ('Active', 'Active'),
        ('Inactive', 'Inactive')
    )
    name = models.CharField(max_length=50, null=True)
    days = models.IntegerField(null=True)
    type = models.CharField(max_length=20, null=True)
    status = models.CharField(max_length=20, null=True, choices=STATUS)


class Workout(models.Model):
    plan = models.ForeignKey(WorkoutPlan, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, null=True)
    target = models.CharField(max_length=50, null=True)


class Sets(models.Model):
    exercise = models.CharField(max_length=100, null=True)
    workout = models.ForeignKey(Workout, null=True, on_delete=models.CASCADE)
    reps_or_time = models.IntegerField(null=True)
    sets = models.IntegerField(null=True)

workout/forms.py
from .models import WorkoutPlan,  Workout, Sets
from django import forms


class WorkoutPlanForm(forms.ModelForm):
    class Meta:
        model = WorkoutPlan
        fields = ['name', 'type', 'days']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Name of plan'}),
            'type': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Type'}),
            'days': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Days / Week'}),
        }


class WorkoutForm(forms.ModelForm):
    class Meta:
        model = Workout
        fields = ['name', 'target']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Workout Name'}),
            'target': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Target Muscles'}),
        }


class ExerciseForm(forms.ModelForm):
    class Meta:
        model = Sets
        fields = ['exercise', 'reps_or_time', 'sets']
        widgets = {
            'exercise': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Exercise'}),
            'reps_or_time': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Reps/Time'}),
            'sets': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sets'}),
        }

landing/views.py
from django.shortcuts import render
from workout.models import WorkoutPlan


def index(request):
    active_plan = WorkoutPlan.objects.get(status='Active')
    context = {'plan': active_plan}
    return render(request, 'landing/index.html', context)

workout/views.py
from django.shortcuts import render, redirect
from .models import WorkoutPlan, Workout, Sets
from .forms import WorkoutPlanForm, WorkoutForm, ExerciseForm
import csv
from datetime import datetime


def index(request):
    plans = WorkoutPlan.objects.all()
    context = {'all_plans': plans}
    return render(request, 'workout/index.html', context)


def add_plan(request):
    form = WorkoutPlanForm()
    if request.method == 'POST':
        form = WorkoutPlanForm(request.POST)
        if form.is_valid():
            p = form.save(commit=False)
            p.status = 'Inactive'
            p.save()
            return redirect('plans')
    context = {'form': form}
    return render(request, 'workout/add_plan.html', context)


def make_active(request, pk):
    current = WorkoutPlan.objects.get(status='Active')
    new = WorkoutPlan.objects.get(id=pk)
    current.status = 'Inactive'
    new.status = 'Active'
    current.save()
    new.save()
    return redirect('plans')


def add_workout(request, pk):
    form = WorkoutForm()
    plan = WorkoutPlan.objects.get(id=pk)
    if request.method == 'POST':
        form = WorkoutForm(request.POST)
        if form.is_valid():
            w = form.save(commit=False)
            w.plan = plan
            w.save()
            return redirect('view_plan', pk)
    context = {'form': form}
    return render(request, 'workout/add_workout.html', context)


def view_plan(request, pk):
    plan = WorkoutPlan.objects.get(id=pk)
    all_workouts = Workout.objects.filter(plan=plan)
    context = {'plan': plan, 'all_workouts': all_workouts}
    return render(request, 'workout/view_plan.html', context)


def add_sets(request, pk):
    workout = Workout.objects.get(id=pk)
    form = ExerciseForm()
    if request.method == 'POST':
        form = ExerciseForm(request.POST)
        if form.is_valid():
            w = form.save(commit=False)
            w.workout = workout
            w.save()
            if request.POST.get('addnewafterthis') == 'on':
                return redirect('add_sets', pk)
            
            return redirect('view_plan', str(workout.plan.id))
    context = {'form': form}
    return render(request, 'workout/add_sets.html', context)


def play_workout(request, pk):
    workout = Workout.objects.get(id=pk)
    if request.method == 'POST':
        time_now = datetime.now()
        with open('workout_log.csv', 'a') as log_file:
            writer = csv.writer(log_file)
            for sub in request.POST:
                if sub != 'csrfmiddlewaretoken':
                    set_id = sub.split('-')[1]
                    print(set_id)
                    set = Sets.objects.get(id=set_id)
                    writer.writerow([str(set.exercise), f'{set.sets}x{set.reps_or_time}', time_now])
                    print(sub)
        return redirect('view_plan', str(workout.plan.id))
    context = {'workout': workout}
    return render(request, 'workout/play_workout.html', context)

landing/templates/landing/base.html
{% load static %}
{% url 'landing' as landing %}
{% url 'plans' as plans %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'assets/img/apple-icon.png' %}">
  <link rel="icon" type="image/png" href="{% static 'assets/img/favicon.png' %}">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>
    CurlMD - An opens source workout planner app
  </title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <!--     Fonts and icons     -->
  <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css">
  <!-- CSS Files -->
  <link href="{% static 'assets/css/material-dashboard.css' %}" rel="stylesheet" />
</head>

<body class="dark-edition">
  <div class="wrapper ">
    <div class="sidebar" data-color="orange" data-background-color="black">
      <!--
        Tip 1: You can change the color of the sidebar using: data-color="purple | azure | green | orange | danger"

        Tip 2: you can also add an image using data-image tag
    -->
      <div class="logo"><a href="#" class="simple-text logo-normal">
          CurlMD
        </a></div>
      <div class="sidebar-wrapper">
        <ul class="nav">
          <li class="nav-item {% if request.path == landing %} active {% endif %}">
            <a class="nav-link" href="{% url 'landing' %}">
              <i class="material-icons">dashboard</i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="nav-item  {% if request.path == plans %} active {% endif %}">
            <a class="nav-link" href="{% url 'plans' %}">
              <i class="material-icons">assignment</i>
              <p>Workout Plans</p>
            </a>
          </li>
          <li class="nav-item ">
            <a class="nav-link" href="{% url 'add_plan' %}">
              <i class="material-icons">add_task</i>
              <p>Add New Plan</p>
            </a>
          </li>
        </ul>
      </div>
    </div>
    <div class="main-panel">
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-transparent navbar-absolute fixed-top " id="navigation-example">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <a class="navbar-brand" href="javascript:void(0)">Dashboard</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation" data-target="#navigation-example">
            <span class="sr-only">Toggle navigation</span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
            <span class="navbar-toggler-icon icon-bar"></span>
          </button>
          <div class="collapse navbar-collapse justify-content-end">
            <form class="navbar-form">
              <div class="input-group no-border">
                <input type="text" value="" class="form-control" placeholder="Search...">
                <button type="submit" class="btn btn-default btn-round btn-just-icon">
                  <i class="material-icons">search</i>
                  <div class="ripple-container"></div>
                </button>
              </div>
            </form>
          </div>
        </div>
      </nav>
      <!-- End Navbar -->
      {% block content %}
      {% endblock %}
      <footer class="footer">
        <div class="container-fluid">
          <nav class="float-left">
            <ul>
              <li>
                <a href="#">
                  CurlMD
                </a>
              </li>
              <li>
                <a href="#">
                  Github
                </a>
              </li>
            </ul>
          </nav>
          <div class="copyright float-right" id="date">
            , CurlMd. Huge Thanks to
            <a href="https://www.creative-tim.com" target="_blank">Creative Tim</a> for frontend.
          </div>
        </div>
      </footer>
      <script>
        const x = new Date().getFullYear();
        let date = document.getElementById('date');
        date.innerHTML = '&copy; ' + x + date.innerHTML;
      </script>
    </div>
  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'assets/js/core/jquery.min.js' %}"></script>
  <script src="{% static 'assets/js/core/popper.min.js' %}"></script>
  <script src="{% static 'assets/js/core/bootstrap-material-design.min.js' %}"></script>
  <script src="https://unpkg.com/default-passive-events"></script>
  <script src="{% static 'assets/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!-- Place this tag in your head or just before your close body tag. -->
  <script async defer src="https://buttons.github.io/buttons.js"></script>
  <!-- Chartist JS -->
  <script src="{% static 'assets/js/plugins/chartist.min.js' %}"></script>
  <!--  Notifications Plugin    -->
  <script src="{% static 'assets/js/plugins/bootstrap-notify.js' %}"></script>
  <!-- Control Center for Material Dashboard: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'assets/js/material-dashboard.js' %}"></script>
  <script>
    $(document).ready(function() {
      $().ready(function() {
        $sidebar = $('.sidebar');

        $sidebar_img_container = $sidebar.find('.sidebar-background');

        $full_page = $('.full-page');

        $sidebar_responsive = $('body > .navbar-collapse');

        window_width = $(window).width();

        $('.fixed-plugin a').click(function(event) {
          // Alex if we click on switch, stop propagation of the event, so the dropdown will not be hide, otherwise we set the  section active
          if ($(this).hasClass('switch-trigger')) {
            if (event.stopPropagation) {
              event.stopPropagation();
            } else if (window.event) {
              window.event.cancelBubble = true;
            }
          }
        });

        $('.fixed-plugin .active-color span').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-color', new_color);
          }

          if ($full_page.length != 0) {
            $full_page.attr('filter-color', new_color);
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.attr('data-color', new_color);
          }
        });

        $('.fixed-plugin .background-color .badge').click(function() {
          $(this).siblings().removeClass('active');
          $(this).addClass('active');

          var new_color = $(this).data('background-color');

          if ($sidebar.length != 0) {
            $sidebar.attr('data-background-color', new_color);
          }
        });

        $('.fixed-plugin .img-holder').click(function() {
          $full_page_background = $('.full-page-background');

          $(this).parent('li').siblings().removeClass('active');
          $(this).parent('li').addClass('active');


          var new_image = $(this).find("img").attr('src');

          if ($sidebar_img_container.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            $sidebar_img_container.fadeOut('fast', function() {
              $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
              $sidebar_img_container.fadeIn('fast');
            });
          }

          if ($full_page_background.length != 0 && $('.switch-sidebar-image input:checked').length != 0) {
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $full_page_background.fadeOut('fast', function() {
              $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
              $full_page_background.fadeIn('fast');
            });
          }

          if ($('.switch-sidebar-image input:checked').length == 0) {
            var new_image = $('.fixed-plugin li.active .img-holder').find("img").attr('src');
            var new_image_full_page = $('.fixed-plugin li.active .img-holder').find('img').data('src');

            $sidebar_img_container.css('background-image', 'url("' + new_image + '")');
            $full_page_background.css('background-image', 'url("' + new_image_full_page + '")');
          }

          if ($sidebar_responsive.length != 0) {
            $sidebar_responsive.css('background-image', 'url("' + new_image + '")');
          }
        });

        $('.switch-sidebar-image input').change(function() {
          $full_page_background = $('.full-page-background');

          $input = $(this);

          if ($input.is(':checked')) {
            if ($sidebar_img_container.length != 0) {
              $sidebar_img_container.fadeIn('fast');
              $sidebar.attr('data-image', '#');
            }

            if ($full_page_background.length != 0) {
              $full_page_background.fadeIn('fast');
              $full_page.attr('data-image', '#');
            }

            background_image = true;
          } else {
            if ($sidebar_img_container.length != 0) {
              $sidebar.removeAttr('data-image');
              $sidebar_img_container.fadeOut('fast');
            }

            if ($full_page_background.length != 0) {
              $full_page.removeAttr('data-image', '#');
              $full_page_background.fadeOut('fast');
            }

            background_image = false;
          }
        });

        $('.switch-sidebar-mini input').change(function() {
          $body = $('body');

          $input = $(this);

          if (md.misc.sidebar_mini_active == true) {
            $('body').removeClass('sidebar-mini');
            md.misc.sidebar_mini_active = false;

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar();

          } else {

            $('.sidebar .sidebar-wrapper, .main-panel').perfectScrollbar('destroy');

            setTimeout(function() {
              $('body').addClass('sidebar-mini');

              md.misc.sidebar_mini_active = true;
            }, 300);
          }

          // we simulate the window Resize so the charts will get updated in realtime.
          var simulateWindowResize = setInterval(function() {
            window.dispatchEvent(new Event('resize'));
          }, 180);

          // we stop the simulation of Window Resize after the animations are completed
          setTimeout(function() {
            clearInterval(simulateWindowResize);
          }, 1000);

        });
      });
    });
  </script>
  <script>
    $(document).ready(function() {
      // Javascript method's body can be found in assets/js/demos.js
      md.initDashboardPageCharts();

    });
  </script>
</body>

</html>

landing/templates/landing/index.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="content">
  <div class="container-fluid">
    <div class="row">
<!--      <div class="col-xl-4 col-lg-12">-->
<!--        <div class="card card-chart">-->
<!--          <div class="card-header card-header-success">-->
<!--            <div class="ct-chart" id="dailySalesChart"></div>-->
<!--          </div>-->
<!--          <div class="card-body">-->
<!--            <h4 class="card-title">Weight Lifted</h4>-->
<!--            <p class="card-category">-->
<!--              <span class="text-success"><i class="fa fa-long-arrow-up"></i> 10% </span> increase in weight lifted than last week</p>-->
<!--          </div>-->
<!--          <div class="card-footer">-->
<!--            <div class="stats">-->
<!--              <i class="material-icons">access_time</i> updated 4 minutes ago-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </div>-->
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-info">
            <h4 class="card-title">Current Plan - {{plan.name}}</h4>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead class="text-warning">
                <tr>
                  <th></th>
                  <th>Name</th>
                  <th>Target Muscle</th>
                  <th>Exercises</th>
                </tr>
              </thead>
              <tbody>
              {% for w in plan.workout_set.all %}
                <tr>
                  <td><a href="{% url 'play_workout' w.id %}" class="btn btn-info btn-sm">Start</a></td>
                  <td>{{w.name}}</td>
                  <td>{{w.target}}</td>
                  <td>{{w.sets_set.all.count}}</td>
                </tr>
              {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

workout/templates/workout/add_plan.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card card-nav-tabs text-center">
          <div class="card-header card-header-primary">
            Create A New Workout Plan
          </div>
          <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row my-5">
                    <div class="col">
                        {{form.name}}
                    </div>
                    <div class="col">
                        {{form.days}}
                    </div>
                </div>
                <div class="row my-5">
                    <div class="col">
                        {{form.type}}
                    </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Add Plan">
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

workout/templates/workout/add_sets.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card card-nav-tabs text-center">
          <div class="card-header card-header-primary">
            Add Exercise Sets
          </div>
          <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div id="items-form-container">
                    <div class="row my-5 item-{{ forloop.counter0 }}">
                        <div class="col f">
                            <label>Exercise</label>
                            {{form.exercise}}
                        </div>
                        <div class="col f">
                            <label>Sets</label>
                            {{form.sets}}
                        </div>
                        <div class="col f">
                            <label>Reps</label>
                            {{form.reps_or_time}}
                        </div>
                    </div>
                </div>
                <div class="form-check">
                  <label class="form-check-label">
                    <input class="form-check-input" type="checkbox" checked name="addnewafterthis">
                        Add New After This
                    <span class="form-check-sign">
                      <span class="check"></span>
                    </span>
                  </label>
                </div>
                <input type="submit" class="btn btn-primary" value="Add Set">
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

workout/templates/workout/add_workout.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card card-nav-tabs text-center">
          <div class="card-header card-header-primary">
            Create A New Workout
          </div>
          <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <div class="row my-5">
                    <div class="col">
                        {{form.name}}
                    </div>
                    <div class="col">
                        {{form.target}}
                    </div>
                </div>
                <input type="submit" class="btn btn-primary" value="Add Plan">
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

workout/templates/workout/index.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="content">
  <div class="container-fluid">
    <div class="row">
      {% for plan in all_plans %}
      <div class="col-xl-4 col-lg-12">
        <div class="card">
          <div class="card-header {% if plan.status == 'Active' %} card-header-success {% else %} card-header-primary {% endif %}">
            <h4 class="card-title">{{plan.name}}</h4>
          </div>
          <div class="card-body">
            <h4 class="card-title">Days: {{plan.days}}</h4>
            <p class="card-category">Type: {{plan.type}}</p>
            {% if plan.status == 'Active' %}
              <button class="btn btn-success btn-sm">Active</button>
            {% else %}
              <a href="{% url 'make_active' plan.id %}" class="btn btn-info btn-sm">Make Active</a>
            {% endif %}
            <a href="{% url 'view_plan' plan.id %}" class="btn btn-primary btn-sm">View</a>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}

workout/templates/workout/play_workout.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="card card-nav-tabs text-left">
          <div class="card-header card-header-primary">
              {{workout.name}} - {{workout.plan.name}}
          </div>
          <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% for exercise in workout.sets_set.all %}
                    <h3>{{exercise.exercise}} - {{exercise.sets}} x {{exercise.reps_or_time}}</h3>
                    <div class="form-check">
                      <label class="form-check-label">
                          <input class="form-check-input" type="checkbox" name="set-{{exercise.id}}" value="">
                          Done
                          <span class="form-check-sign">
                              <span class="check"></span>
                          </span>
                      </label>
                    </div>
                <br />
                {% endfor %}
                <input type="submit" class="btn btn-primary" value="Finish Workout">
            </form>
          </div>
        </div>
    </div>
</div>
{% endblock %}

workout/templates/workout/view_plan.html
{% extends 'landing/base.html' %}

{% block content %}
<div class="content">
  <div class="container-fluid">
    <div>
      <h3 class="text-white">{{plan.name}}</h3>
      <a href="{% url 'add_workout' plan.id %}" class="btn btn-primary">Add Workout</a>
    </div>
    <div class="row my-5">
      {% for workout in all_workouts %}
      <div class="col-xl-4 col-lg-12">
        <div class="card">
          <div class="card-header card-header-info">
            <h4 class="card-title">{{workout.name}}</h4>
          </div>
          <div class="card-body">
            <h4 class="card-title">Target Muscles: {{workout.target}}</h4>
            <ul>
              {% for set in workout.sets_set.all %}
                <li>{{set.exercise}}</li>
              {% endfor %}
            </ul>
            <a href="{% url 'play_workout' workout.id %}" class="btn btn-sm rounded-3 btn-success">Play Workout</a>
            <a href="{% url 'add_sets' workout.id %}" class="btn btn-primary btn-sm">Add Sets</a>
            <button class="btn btn-info btn-sm">Edit</button>
            <button class="btn btn-danger btn-sm">Delete</button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</div>
{% endblock %}